version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
       MYSQL_DATABASE: bookapi
       MYSQL_USER: app
       MYSQL_PASSWORD: password
       MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: user_password
    networks:
      - app-network
    volumes:
      - ./api:/var/www
    expose:
      - 8000   # Updated to expose port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build: ./client
    container_name: client
    networks:
      - app-network
    expose:
      - 3000
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - client
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
