name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-api:
    name: Build and Push API Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (required for advanced Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push the API Docker image
    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./api           # Path to your API Dockerfile
        file: ./api/Dockerfile    # Dockerfile location
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bookapi:latest

  build-and-push-client:
    name: Build and Push Client Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push the Client Docker image
    - name: Build and push Client Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./client         # Path to your Client Dockerfile
        file: ./client/Dockerfile  # Dockerfile location
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nuxtclient:latest
